//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EasyPOS.Resources
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class easyposEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new easyposEntities object using the connection string found in the 'easyposEntities' section of the application configuration file.
        /// </summary>
        public easyposEntities() : base("name=easyposEntities", "easyposEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new easyposEntities object.
        /// </summary>
        public easyposEntities(string connectionString) : base(connectionString, "easyposEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new easyposEntities object.
        /// </summary>
        public easyposEntities(EntityConnection connection) : base(connection, "easyposEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<statement> statements
        {
            get
            {
                if ((_statements == null))
                {
                    _statements = base.CreateObjectSet<statement>("statements");
                }
                return _statements;
            }
        }
        private ObjectSet<statement> _statements;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the statements EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTostatements(statement statement)
        {
            base.AddObject("statements", statement);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="easyposModel", Name="statement")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class statement : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new statement object.
        /// </summary>
        /// <param name="debit">Initial value of the Debit property.</param>
        /// <param name="credit">Initial value of the Credit property.</param>
        public static statement Createstatement(global::System.Double debit, global::System.Double credit)
        {
            statement statement = new statement();
            statement.Debit = debit;
            statement.Credit = credit;
            return statement;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Naration
        {
            get
            {
                return _Naration;
            }
            set
            {
                OnNarationChanging(value);
                ReportPropertyChanging("Naration");
                _Naration = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Naration");
                OnNarationChanged();
            }
        }
        private global::System.String _Naration;
        partial void OnNarationChanging(global::System.String value);
        partial void OnNarationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Debit
        {
            get
            {
                return _Debit;
            }
            set
            {
                if (_Debit != value)
                {
                    OnDebitChanging(value);
                    ReportPropertyChanging("Debit");
                    _Debit = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Debit");
                    OnDebitChanged();
                }
            }
        }
        private global::System.Double _Debit;
        partial void OnDebitChanging(global::System.Double value);
        partial void OnDebitChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Credit
        {
            get
            {
                return _Credit;
            }
            set
            {
                if (_Credit != value)
                {
                    OnCreditChanging(value);
                    ReportPropertyChanging("Credit");
                    _Credit = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Credit");
                    OnCreditChanged();
                }
            }
        }
        private global::System.Double _Credit;
        partial void OnCreditChanging(global::System.Double value);
        partial void OnCreditChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Balance
        {
            get
            {
                return _Balance;
            }
            set
            {
                OnBalanceChanging(value);
                ReportPropertyChanging("Balance");
                _Balance = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Balance");
                OnBalanceChanged();
            }
        }
        private Nullable<global::System.Double> _Balance;
        partial void OnBalanceChanging(Nullable<global::System.Double> value);
        partial void OnBalanceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String user
        {
            get
            {
                return _user;
            }
            set
            {
                OnuserChanging(value);
                ReportPropertyChanging("user");
                _user = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("user");
                OnuserChanged();
            }
        }
        private global::System.String _user;
        partial void OnuserChanging(global::System.String value);
        partial void OnuserChanged();

        #endregion

    
    }

    #endregion

    
}
